# Generated by Django 5.1.4 on 2025-01-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0018_alter_prova_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('materia', models.ManyToManyField(related_name='Vestibulares', to='app.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaQuestoes.listas')),
            ],
        ),
    ]
