# Generated by Django 5.1.4 on 2025-01-17 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_prova_status'),
        ('listaQuestoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listas',
            name='materia',
        ),
        migrations.AddField(
            model_name='listas',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vestibulares', to='app.materia'),
            preserve_default=False,
        ),
    ]
