# Generated by Django 5.1.4 on 2025-02-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaQuestoes', '0002_remove_listas_materia_listas_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestoesAssinalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('alternativaMarcada', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('DEFAULT', 'DEFAULT')], default='DEFAULT', max_length=20)),
                ('grauDeCerteza', models.CharField(choices=[('CERTEZA', 'CERTEZA'), ('DUVIDA', 'DUVIDA'), ('CHUTE', 'CHUTE'), ('DEFAULT', 'DEFAULT')], default='DEFAULT', max_length=20)),
                ('simuladoGeral', models.BooleanField()),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaQuestoes.listas')),
            ],
        ),
        migrations.DeleteModel(
            name='Questoes',
        ),
    ]
