# Generated by Django 5.1.4 on 2025-03-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaQuestoes', '0003_listas_tipo_questoesassinalar_delete_questoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoesassinalar',
            name='letraGabarito',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('DEFAULT', 'DEFAULT')], default='DEFAULT', max_length=20),
        ),
    ]
