# Generated by Django 5.1.4 on 2025-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaQuestoes', '0005_questoesassinalar_certoouerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoesassinalar',
            name='gabaritoLancado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
