# Generated by Django 5.1.4 on 2025-03-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaQuestoes', '0007_remove_questoesassinalar_gabaritolancado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoesassinalar',
            name='certoOuErrada',
        ),
        migrations.AddField(
            model_name='questoesassinalar',
            name='certoa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listas',
            name='gabaritoLancado',
            field=models.BooleanField(default=False),
        ),
    ]
