# Generated by Django 5.1.4 on 2025-03-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaQuestoes', '0008_remove_questoesassinalar_certoouerrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questoesassinalar',
            old_name='certoa',
            new_name='certo',
        ),
    ]
