# Generated by Django 5.2 on 2025-05-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMECADO', 'começado'), ('FINALIZADO', 'finalizado'), ('NAOINICIADO', 'não iniciado')], default='NAOINICIADO', max_length=20)),
                ('tempo_gasto', models.TimeField(blank=True, default=None, null=True)),
                ('descricao', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('siglaDaMateria', models.CharField(max_length=20)),
                ('areaPertence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.areasconhecimento')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoRever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoPrecisoVer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('acertou', models.BooleanField()),
                ('tipoAcerto', models.CharField(default='Não acertei', max_length=50)),
                ('tipoErro', models.CharField(default='Não Errei', max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.materia')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
        migrations.CreateModel(
            name='QuestoesErradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letraMarcada', models.CharField(max_length=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questoes')),
            ],
        ),
        migrations.CreateModel(
            name='Vestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('siglaInstituicao', models.CharField(max_length=20)),
                ('qntQuestoes', models.IntegerField()),
                ('areasProva', models.ManyToManyField(related_name='Vestibulares', to='app.areasconhecimento')),
            ],
        ),
        migrations.AddField(
            model_name='prova',
            name='vestibular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vestibular'),
        ),
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(default=' ', max_length=400)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
    ]
