# Generated by Django 5.2 on 2025-05-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
