# Generated by Django 5.1.4 on 2024-12-21 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areasdasmaterias_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='areaPertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.areasdasmaterias'),
            preserve_default=False,
        ),
    ]
