# Generated by Django 5.1.4 on 2024-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_materias_areapertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='siglaDaMateria',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
