# Generated by Django 5.1.4 on 2024-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_materias_sigladamateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('siglaInstituicao', models.CharField(max_length=20)),
                ('qntQuestoes', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Materias',
            new_name='Materia',
        ),
        migrations.DeleteModel(
            name='Vestibulares',
        ),
        migrations.RenameModel(
            old_name='AreasDasMaterias',
            new_name='AreasConhecimento',
        ),
        migrations.AddField(
            model_name='vestibular',
            name='areasProva',
            field=models.ManyToManyField(related_name='Vestibulares', to='app.areasconhecimento'),
        ),
    ]
