# Generated by Django 5.1.4 on 2024-12-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vestibular_rename_materias_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('vestibular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vestibular')),
            ],
        ),
    ]
