# Generated by Django 5.1.4 on 2024-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='nome',
        ),
        migrations.AddField(
            model_name='prova',
            name='ano',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
