# Generated by Django 5.1.4 on 2024-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_prova_nome_prova_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
