# Generated by Django 5.1.4 on 2024-12-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_prova_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoPrecisoVer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoRever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipoAcerto', models.CharField(default='Não acertei', max_length=50)),
                ('tipoErro', models.CharField(default='Não Errei', max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.materia')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(default=' ', max_length=400)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
    ]
