# Generated by Django 5.1.4 on 2024-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_conteudoprecisover_conteudorever_questoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='status',
            field=models.CharField(choices=[('COMECADO', 'Começado'), ('TERMINADO', 'Terminado'), ('NAOINICIADO', 'Não Iniciado')], default='NAOINICIADO', max_length=20),
        ),
    ]
