

# Generated by Django 5.1.4 on 2024-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_prova_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='qntQuestoes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prova',
            name='status',
            field=models.CharField(choices=[('COMECADO', 'começado'), ('finzalizado', 'finalizado'), ('NAOINICIADO', 'não iniciado')], default='NAOINICIADO', max_length=20),
        ),
    ]
