# Generated by Django 5.1.4 on 2024-12-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_prova_qntquestoes_alter_prova_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='qntQuestoes',
        ),
    ]
