# Generated by Django 5.1.4 on 2024-12-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_prova_qntquestoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='acertou',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
