# Generated by Django 5.1.4 on 2024-12-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_questoes_acertou'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestoesErradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letraMarcada', models.CharField(max_length=1)),
                ('questoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questoes')),
            ],
        ),
    ]
