# Generated by Django 5.1.4 on 2024-12-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_questoeserradas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questoeserradas',
            old_name='questoes',
            new_name='questao',
        ),
    ]
