# Generated by Django 5.1.4 on 2025-01-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_conteudoprecisover_prova_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoprecisover',
            name='prova',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.prova'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudorever',
            name='prova',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.prova'),
            preserve_default=False,
        ),
    ]
