# Generated by Django 5.1.4 on 2025-01-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_conteudoprecisover_prova_conteudorever_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='status',
            field=models.CharField(choices=[('COMECADO', 'começado'), ('FINALIZADO', 'finalizado'), ('NAOINICIADO', 'não iniciado')], default='NAOINICIADO', max_length=20),
        ),
    ]
